### ISSUE TITLE
No CSS styling in my browser for docs.

### ISSUE THREAD

**Issue by giantelk** [Semantic-Org/Semantic-UI-Docs#103]
How do I get the CSS styling to work? I got the docpad working to create the static HTML in /docs/, and running `docpad run`, but the CSS isn't showing in my browser, only plain non-styled HTML.

**Comment by jlukic** [comment]
You need to run `gulp build-docs` from the ui directory

**Comment by giantelk** [comment]
I don't see a /ui/ directory anywhere, btw I'm working off branch `1.0`, as that's the branch where `module.html.eco` is that you sent me. And there's no Gulp file, only `Gruntfile.js`.

**Comment by giantelk** [comment]
I tried this again on `master` branch, still no `gulp` file and no `/ui/` directory. Maybe your thinking of the main Semantic UI repo. https://github.com/Semantic-Org/Semantic-UI

This issue is specific to this rep: https://github.com/Semantic-Org/Semantic-UI-Docs

**Comment by jlukic** [comment]
Read the guide, it explains the directory structure..

**Comment by jlukic** [comment]
`Module.html.eco` was from a legacy branch representing `1.0` (coming on to about a year old), be sure to use the `next` branch
