### ISSUE TITLE
build-docs doesn't copy dist\components\*.css

### ISSUE THREAD

**Issue by ichadhr** [Semantic-Org/Semantic-UI-Docs#107]
while running `docpad server` there is bunch of notices file not found:
```
notice: 404 Not Found: /dist/components/progress.css
notice: 404 Not Found: /dist/components/rating.css
notice: 404 Not Found: /dist/components/search.css
notice: 404 Not Found: /dist/components/shape.css
notice: 404 Not Found: /dist/components/sidebar.css
notice: 404 Not Found: /dist/components/sticky.css
notice: 404 Not Found: /dist/components/tab.css
..etc
```
they're all related to *.css files, I think `build-docs` doesn't have job copying these files? so I need manually copy all *.css from ui folder.

**Comment by jlukic** [comment]
Follow the directions here and all will be fine 
http://semantic-ui.com/introduction/advanced-usage.html#running-docs-locally

**Comment by ichadhr** [comment]
Thank You !
