### ISSUE TITLE
Semantic UI Fixed Template ("Fixed Menu" template)

### ISSUE THREAD

**Issue by space-alien** [Semantic-Org/Semantic-UI-Docs#142]
Some weirdness in the [Semantic UI Fixed Template layout](http://semantic-ui.com/examples/fixed.html) example which made my learning experience harder than it perhaps needed to be:

1. ```<div href="#" class="header item">``` - The first menu item is a ```<div>``` with an ```href```
2. ```<a href="#" class="ui simple dropdown item">``` - The entire dropdown menu component is an enormous ```<a>``` tag. This means none of the child item links can be ```<a>``` tags. In the example the child 'links' are just plain ```<div>```s, which is not a great starting point. Also, touch users would presumably not be able to use the dropdown - tapping it would trigger the link rather than opening the menu.
3. Perhaps the parent ```<div>``` could be a ```<nav>``` tag.

Here is the code for the menu incorporating all the above changes and making use of ```<a>``` tags for all links. I would have submitted a pull request but I couldn't find the examples code anywhere in this repo (which is perhaps [a separate issue](https://github.com/Semantic-Org/Semantic-UI-Docs/issues/125))

```
  <nav class="ui fixed inverted menu">
    <div class="ui container">
      <a href="#" class="header item">
        <img class="logo" src="assets/images/logo.png">
        Project Name
      </a>
      <a href="#" class="item">Home</a>
      <div class="ui simple dropdown item">
        Dropdown <i class="dropdown icon"></i>
        <div class="menu">
          <a href="#" class="item">Link Item</a>
          <a href="#" class="item">Link Item</a>
          <div class="divider"></div>
          <div class="header">Header Item</div>
          <div class="item">
            <i class="dropdown icon"></i>
            Sub Menu
            <div class="menu">
              <a href="#" class="item">Link Item</a>
              <a href="#" class="item">Link Item</a>
            </div>
          </div>
          <a href="#" class="item">Link Item</a>
        </div>
      </div>
    </div>
  </nav>
```

**Comment by jlukic** [comment]
Sorry those were pretty awful oversights
https://github.com/Semantic-Org/Semantic-UI/commit/f795d2d31986b45c40b716027564b26f5b3cf0a9
