### ISSUE TITLE
[Discussion] How the language is changed on runtime? 

### ISSUE THREAD

**Issue by skylee91** [Semantic-Org/Semantic-UI-Docs#148]
I noticed that when I click on the button called Change Language.
The language list will be shown. After I selected a language, Chinese, the page will be changed to Chinese. 
Some of the strings are remained to English whereas some strings are changed to Chinese.

Could I know how this process is done?
I searched the code but I cannot figure why.

1. How to the mapping between current language to target language?
2. Where is the content of target language stored?
3. Where is the method to change language?

Thanks

**Comment by IonutBajescu** [comment]
If you want to contribute to the translations you may want to check out this page https://github.com/Semantic-Org/Semantic-UI/wiki/Translating-Semantic-UI-Docs
