### ISSUE TITLE
License on Avataars

### ISSUE THREAD

**Issue by neil-s** [Semantic-Org/Semantic-UI-Docs#153]
I'm building an MVP for a project, in which I want to explain some features and need mock avataars in the demonstrations. The avataars used in these docs looked ideal.

Is there a license on reusing the avataars here, for our own, potentially commercial, projects? Alternatively, anyone have recommendations on where I could generate my own, especially since I need one of an elderly lady?

**Comment by jlukic** [comment]
They are modified versions of these images.
https://creativemarket.com/Jesussanz/29769-Flat-Avatar-Collection.-Cool-People

[Artica](https://creativemarket.com/blog/2014/07/28/featured-shop-artica) is a great artist please pass along your support with a license purchase.

**Comment by neil-s** [comment]
Thanks for the quick response @jlukic . I'll revisit Artica the moment we start making some money and have a better budget for creative assets.
