### ISSUE TITLE
Instructions adequate to build docs?

### ISSUE THREAD

**Issue by jasonVeld** [Semantic-Org/Semantic-UI-Docs#167]
Instructions mention a ui folder, a docs folder, a vendor folder, and grunt files, but none of these were found. Missing semantics in the instructions? Nearest I got to getting it to work was using the command "docpad run" which generated the site to ./out, but errors were generated along the way, which would account for the generated pages lacking correct styling.

**Comment by jlukic** [comment]
I'm not sure what directions you're following, but we dont use grunt. 

See docs here
http://semantic-ui.com/introduction/advanced-usage.html#download-docs-server

**Comment by jasonVeld** [comment]
Thanks for the link for docs by git clone (though not tried yet). fyi, from your front page here:

"Then you should put docs/ under vendor/
...
gulp build-docs"

There's no docs folder as such, perhaps its server/documents, and no build-docs file for gulp to run, at least in the zip downloaded from github.
