### ISSUE TITLE
Version number  in black button on homepage hero states 1.7.2

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI-Docs#19]
Just updated the ```ui``` and ```docs``` repos to the latest.

The online docs site has 1.7.3 in the black button in the homepage hero.
The offline docs site has 1.7.2 in the black button in the homepage hero.

Version 1.7.2 is confirmed with what's here in the Docs repo:
https://github.com/Semantic-Org/Semantic-UI-Docs/blob/5cd35ad212bb4811cbf6fb92c1d6bbb74d302d7b/docpad.coffee#L32

So am I looking at the same docs with just a typo in the version number?
Or is the offline Docs repo trailing 0.0.1 behind the version online ?

**Comment by jlukic** [comment]
I have to manually update the version number in the docs when i deploy. The rest of the docs in master are up to date with the latest released changes to SUI.

**Comment by Lisa-Williams** [comment]
Ah, thanks for clearing that one up.
So the docs are up to date.
