### ISSUE TITLE
A typo in module dropdown

### ISSUE THREAD

**Issue by xiechao06** [Semantic-Org/Semantic-UI-Docs#20]
option **fullTextSearch**'s default value should be **false** (https://github.com/Semantic-Org/UI-Dropdown/blob/master/dropdown.js), but in document it is **true**(http://semantic-ui.com/modules/dropdown.html#/settings)

**Comment by jlukic** [comment]
Sorry about that. fixed

![Picard](http://media.giphy.com/media/qTXG8R4OtbQPu/giphy.gif)
