### ISSUE TITLE
Bugs on Grid page

### ISSUE THREAD

**Issue by airandfingers** [Semantic-Org/Semantic-UI-Docs#210]
On [Grid](http://semantic-ui.com/collections/grid.html), if you click "Definition", then click any of the navigation links on the right, you're taken back to top of the the "Overview" page, 

Also, the second "Text Alignment" Grid example (under "Definition") doesn't work; the center column is apparently supposed to override the grid's "center aligned" classes with its own "left aligned" classes, but instead everything is centered.

**Comment by Banandrew** [comment]
Hi @airandfingers, everything seems to be in order, can you please confirm?

**Comment by airandfingers** [comment]
Looks good now!
