### ISSUE TITLE
Search module settings have typos

### ISSUE THREAD

**Issue by miniskulljob** [Semantic-Org/Semantic-UI-Docs#25]
Hi.

The doc page about the Search module has some typos:
* minCharacters says its default value is 2, but it is 1 according to the module code ([line 874](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L874))
* hideDelay default value is 0, not 300 ([line 887](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L887))
* searchDelay default value is 100, not 300 ([line 888](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L888))
* verbose default value is true, not false ([line 870](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L870))
* performance default value is true, not false ([line 871](https://github.com/Semantic-Org/Semantic-UI/blob/master/src/definitions/modules/search.js#L871))

**Comment by jlukic** [comment]
Thanks for contributing, and sorry about that. Looks like I forgot to update the changes.

**Comment by jlukic** [comment]
Deploying with changes now
