### ISSUE TITLE
Reference to CDN file is broken.

### ISSUE THREAD

**Issue by sunnykgupta** [Semantic-Org/Semantic-UI-Docs#273]
https://cdn.jsdelivr.net/semantic-ui/2.2.7/semantic.min.css

As referred on http://semantic-ui.com/introduction/advanced-usage.html is broken.

**Comment by IonutBajescu** [comment]
The link appears to work now.

**Comment by gmlion** [comment]
It's broken again.
Working links starts with https://cdn.jsdelivr.net/npm/semantic-ui@2.2.13/dist
