### ISSUE TITLE
Add search and keyboard shortcuts

### ISSUE THREAD

**Issue by pcj** [Semantic-Org/Semantic-UI-Docs#30]
I feel I am constantly clicking the menu (slide open...), Cmd-F'ing chrome, and finding the section that I am looking for.  It would be a usability improvement to add a search function to the documentation site, as well as keyboard shortcuts.  I recommend the similar convention to https://help.github.com/articles/using-keyboard-shortcuts.

If desired, I can start on it.  Pls suggest best way to grep code and generate json file like `{ title: '', description: ''}` for `.fn.search`.

**Comment by jlukic** [comment]
I think that's an excellent idea, thanks for the suggestion. 

Pages [include metadata](https://github.com/Semantic-Org/Semantic-UI-Docs/blob/master/server/documents/collections/grid.html.eco#L2) but this metadata doesnt include data about `types`, `variations` etc.

Titles always match  `<h4 class="ui header">` in docs though, probably can grep on that. You won't get more details. If you were scraping you could find out the classification by finding each `<h2>` before an `<h4>`, but that would require some sort of automation.

**Comment by pcj** [comment]
OK, I've modified the build.js script for the buildDocs task to scrape the html.eco files, extract the yaml frontmatter, assemble this into a metadata.json file.

I've then updated the fixed-menu template to create a search input item that loads the metadata.json and displays that to the user.

Finally, I've added keyboard shortcut support with jquery.hotkeys.js.

I'll file the PRs tomorrow to review. That docpad sure is damn slow.

**Comment by jlukic** [comment]
Yeah it's cripplingly slow... Be sure to PR changes into next branch if you can.

**Comment by pcj** [comment]
OK PRs have been submitted. The UI looked fine in my local branch `search`, but a little wonky once I rebased onto `next`, but the functionality I introduced does not appear to be the culprit.  Let me know if there are issues.  You may want to spiff up the appearance of the modal and/or move the location of the search input.
