### ISSUE TITLE
[Sidebar] How to make same sidebar as on docs page?

### ISSUE THREAD

**Issue by strejcradis** [Semantic-Org/Semantic-UI-Docs#334]
Hi guys,

please help me. Im not able to recreate the sidebar as its used in documentation (both mobile and desktop pc sidebar). Please, could you help me to extract code and recreate it? What do I need?

Thanks

**Comment by Banandrew** [comment]
Hi @strejcradis, the documentation uses two sidebars: one is visible only on desktops and uses custom CSS—[here’s](http://jsfiddle.net/Banandrew/9uL6g1hp/) an old Flexbox example— the other one is visible only on mobiles and uses SUI’s sidebar component. You’ll need to add the sidebar component to the example, then write media-queries for both to hide/show them at different breakpoints.

Thank you for posting, but although it’s a valid usage question, we’ve limited GitHub Issues to bug reports and feature requests, keeping the board more manageable for maintainers; see the [contributing guidelines](https://github.com/Semantic-Org/Semantic-UI/blob/master/CONTRIBUTING.md) for more information on what kind of posts should find themselves into the GitHub Issues board.

To get answers or feedback that might allow you to repost or reopen this issue, please use one of our other support resources:
* [Gitter chatroom](https://gitter.im/Semantic-Org/Semantic-UI)
* [Official forums](http://forums.semantic-ui.com)
* [StackOverflow](http://stackoverflow.com/questions/tagged/semantic-ui)
