### ISSUE TITLE
Outdated download page

### ISSUE THREAD

**Issue by samjudge** [Semantic-Org/Semantic-UI-Docs#365]
If you perform a search along the lines of "semantic ui download" on google (or other search engine) there is a chance you may end up on [this](https://semantic-ui.com/download) page, which links to a horribly outdated semantic ui distribution (Looks like it's from around 2014). The version available here breaks with several of the modules outlined in the docs (Using jQuery 3.x.x), so maybe a redirect to the getting stared page would be better (where a more recent version is available)?

**Comment by jlukic** [comment]
I'll remove these pages
