### ISSUE TITLE
code reveal bug on elements/image/variations/avatar

### ISSUE THREAD

**Issue by dodekeract** [Semantic-Org/Semantic-UI-Docs#38]
Hi, I found this bug related to revealing the example code:
1. Go to http://semantic-ui.com/elements/image.html
2. Reveal code for Variations/Avatar.
3. Notice the Username appears on top of the avatar image.

Browser: Google Chrome 42.0.2311.135m, Windows 8 Pro 64-bit

**Comment by jlukic** [comment]
Hey, this is fixed in `next` but not live site. Will go with June 1st launch of `2.0`.

**Comment by jlukic** [comment]
Thanks, fixed
