### ISSUE TITLE
Bath icon is listed in the Code section

### ISSUE THREAD

**Issue by faheel** [Semantic-Org/Semantic-UI-Docs#401]
[![screenshot from 2018-08-17 20-07-32](https://user-images.githubusercontent.com/11466676/44272048-5f551280-a259-11e8-8ecd-199b0d649891.png)](https://semantic-ui.com/elements/icon.html#code)

/r/hmm :thinking:

**Comment by hammy2899** [comment]
This is because it is on the FontAwesome page https://fontawesome.com/icons?d=gallery&s=brands,regular,solid&c=code&m=free
