### ISSUE TITLE
503 Error On Page Load

### ISSUE THREAD

**Issue by CrispyBacon1999** [Semantic-Org/Semantic-UI-Docs#409]
Any time I go to load a page on the docs, 90% of the time I will get a 503 error. If I refresh, most of the time it will load perfectly fine, but sometimes it takes a few attempts.

**Comment by hammy2899** [comment]
This is a problem with GitHub not SUI.

**Comment by CrispyBacon1999** [comment]
I was told to ask by github even though there was clearly nothing you guys could do about their hosting.
