### ISSUE TITLE
Edit This Page

### ISSUE THREAD

**Issue by jlukic** [Semantic-Org/Semantic-UI-Docs#59]
UI Examples (+ missing space between the buttons and the page tabs)
The 2 "Globals" pages (no missing space here)
The 3 "Behaviors" pages (+ missing space between the buttons and the page tabs)

**Comment by lemartialou** [comment]
#60 should add the button to the "Globals" and "Behaviors" pages

Not sure about the "UI examples" page, the `@document.type` in `kitchen-sink.html.eco` is "Semantic", shouldn't it be something more like "UI examples" or "UI Kitchen-sink" ?

**Comment by jlukic** [comment]
The document type was never used for anything, so "semantic" is just a junk value.

**Comment by lemartialou** [comment]
So to close this issue I created:

#64 to add a meaningful document type on the kitchen-sink page for the conditional in the header
#65 add the UI Examples page to the conditional in the header

#66 would be an alternative to #65, simply removing the conditional so the buttons appear everywhere

Modifying the UI Examples page may need additional buttons on each example to be completely useful, maybe a button next to the "view source" redirecting to the examples partials, what do you think?

**Comment by jlukic** [comment]
Added PR
