### ISSUE TITLE
Bulleted list items not displaying properly

### ISSUE THREAD

**Issue by richarddewit** [Semantic-Org/Semantic-UI-Docs#62]
Bullets are shown as their plain-text `â€¢` instead of a bullet.

http://semantic-ui.com/elements/list.html

![image](https://cloud.githubusercontent.com/assets/7933750/7979889/7368c826-0aa3-11e5-8dad-813cd8fd7d05.png)

**Comment by jlukic** [comment]
What browser?

**Comment by richarddewit** [comment]
Google Chrome 43 (Linux)

Probably some rendering glitch as it is now correct again after refreshing.
