### ISSUE TITLE
Some spotted display bugs

### ISSUE THREAD

**Issue by lemartialou** [Semantic-Org/Semantic-UI-Docs#67]
http://beta.semantic-ui.com/elements/divider.html
![Imgur](http://i.imgur.com/CLY53RU.png)

http://beta.semantic-ui.com/modules/transition.html#/definition
http://beta.semantic-ui.com/modules/transition.html#/examples
http://beta.semantic-ui.com/modules/transition.html#/usage
![Imgur](http://i.imgur.com/yd3BzKu.png)

http://beta.semantic-ui.com/behaviors/api.html#/usage
![Imgur](http://i.imgur.com/ptCqKuX.png)

**Comment by jlukic** [comment]
Thanks, I'll be addressing these. Trying to find a way to fit in an additional column of content for 3 column views still..

**Comment by lemartialou** [comment]
I guess you'll have to remove the sticky menu like on the Rail, Sidebar, Sticky, etc... pages (c.f. [current docs](http://semantic-ui.com/behaviors/api.html#/usage)). Can't think of a better solution right now.

**Comment by jlukic** [comment]
I've fixed layouts with examples and the `vertical divider` example. 25062a9428a18a133208676fa529b375b99a8fed a3283bc772bfa5ee8f2e8a731d079fb1ba43ca72
