### ISSUE TITLE
How to edit code examples in the docs?

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Docs#76]
Eg, I want to edit http://semantic-ui.com/elements/icon.html#message example

**Comment by jlukic** [comment]
Code is either autogenerated from example html. Or exists in a div called `existing code`. For the icon docs they use `existing code` sections.

**Comment by avalanche1** [comment]
ok.
https://github.com/Semantic-Org/Semantic-UI-Docs/pull/77

**Comment by jlukic** [comment]
Thanks unsure when these got out of date.
