### ISSUE TITLE
Some pages have sidebar toggled by default and no 'Menu' button

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Docs#80]
http://semantic-ui.com/elements/container.html - normal
http://semantic-ui.com/elements/button.html - not normal

**Comment by jlukic** [comment]
Pages that require more than 700px for ostage (rails, sticky) use alternate definition view with closed sidebar by default.

**Comment by avalanche1** [comment]
What do you mean 'for stage'?
I think uniformity sd be preserved among all the pages.
When on one page you have one layout, and on another - another - that really doesn't look nice.

**Comment by jlukic** [comment]
Container, rail, sticky all require much wider page content to show examples. I am happy with the decision.
