### ISSUE TITLE
[Sidebar] - add horizontal sidebar to the examples

### ISSUE THREAD

**Issue by avalanche1** [Semantic-Org/Semantic-UI-Docs#81]
So that Horizontal Only Animations: `Uncover  Slide Along  Slide Out`are demo-able.

**Comment by jlukic** [comment]
That should read "Vertical Only" referring to `left` or `right`. I'll revise now.

**Comment by avalanche1** [comment]
I don't get it: what's the diff bw  `Uncover  Slide Along  Slide Out`? They all loook the same [here](http://semantic-ui.com/modules/sidebar.html#direction).

**Comment by jlukic** [comment]
They are all different animations..
