### ISSUE TITLE
Icon file paths malformed.

### ISSUE THREAD

**Issue by Lisa-Williams** [Semantic-Org/Semantic-UI-Docs#9]
I just build the SUI-docs and SUI-Learn-docs.

The SUI-docs don't show any icons though.
(The SUI-Learn-docs seem to be OK.)

Docpad throws these errors. And it looks like the forward-slash between ```..``` and ```themes``` was lost along the way.

![semanticui-docpad-malformed-font-path_2014-12-28_23-17-35](https://cloud.githubusercontent.com/assets/6225311/5565240/ac7a5c88-8eed-11e4-9038-95c5bdd09f14.png)

This is what the Icons doc page looks like (Icons are missing everywhere though, also on the kitchen sink).

![semanticui-docpad-malformed-font-path_2014-12-28_23-42-23](https://cloud.githubusercontent.com/assets/6225311/5565241/b60bc188-8eed-11e4-83e2-b7830393349d.png)

**Comment by jlukic** [comment]
I think so actually, glad it helped!
